name: Exploring Workflow Dispatch Trigger



on:
  workflow_dispatch:
   inputs:
    run_job:
     type: 'boolean'
     description: 'Run Specific Job'
     required: false

    custom_message:
      type: 'string'
      description: 'Enter a custom message'
      required: true





jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    runs-on: ubuntu-latest

    steps:

      - name: printing custom message
        run: echo "${{ github.event.inputs.custom_message}}"

      - name: Printing run-job boolean value
        if:  ${{ inputs.run_job== 'true' }}
        run: echo "${{ github.event.inputs.run_job}}"  
      